# Top-level Makefile - includes modular makefiles from make.d/
# Generated by split operation to keep the repository organized.

# Default goal
.DEFAULT_GOAL := help

# Ensure includes are loaded
-include scripts/make.d/*.mk

# Provide a short message if includes are missing
ifeq ($(wildcard scripts/make.d/*.mk),)
$(error No include files found in scripts/make.d/ — run the split script or restore original Makefile)
endif

.PHONY: help
