export enum MaterialGroupRoute {
  OXIDES        = 'oxides',
  SILICATES     = 'silicates',
  GLASSES       = 'glasses',
  CLAYS         = 'clays',
  FLUXES        = 'fluxes',
  BINDERS       = 'binders',
  CARBIDES      = 'carbides',
  NITRIDES      = 'nitrides',
  BORIDES       = 'borides',
  FLUORIDES     = 'fluorides',
  BORATES       = 'borates',
  PHOSPHATES    = 'phosphates',
  RARE_EARTHS   = 'rare-earths',
  GLASS_FORMERS = 'glass-formers',
  HYDROXIDES    = 'hydroxides',
  GELS          = 'gels',
  CARBONATES    = 'carbonates',
}
