export enum MaterialGroup {
  OXIDE        = 'oxide',
  SILICATE     = 'silicate',
  GLASS        = 'glass',
  CLAY         = 'clay',
  FLUX         = 'flux',
  BINDER       = 'binder',
  CARBIDE      = 'carbide',
  NITRIDE      = 'nitride',
  BORIDE       = 'boride',
  FLUORIDE     = 'fluoride',
  BORATE       = 'borate',
  PHOSPHATE    = 'phosphate',
  RARE_EARTH   = 'rare_earth',
  GLASS_FORMER = 'glass_former',
  HYDROXIDE    = 'hydroxide',
  GEL          = 'gel',
  CARBONATE    = 'carbonate',
}
