export const MINERAL_COMPOSITIONS_UI = {
  customSizeKey: 'custom',
  massPercentTotal: 100,
  massPercentTolerance: 0.5,
  /** `FractionInputDto.density_kgm3` limits (blend optimiser). */
  densityMin_kgm3: 1000,
  densityMax_kgm3: 4000,
  massDecimals: 2,
  psd: { defaultQ: 0.37, qMin: 0.2, qMax: 0.5, qStep: 0.01, debounce_ms: 300, andreasenDmin_mm: 0 },
  chemistry: {
    defaultTemperature_C: 1400,
    temperatureMin_C: 500,
    temperatureMax_C: 2000,
    defaultTotalMass: 100,
    defaultTestTemperature_C: 1500,
    defaultPorosity: 0.2,
    densePorosity: 0,
    sweep: { from: 1000, to: 1600, step: 50 },
    sweepMaxPoints: 25,
  },
  packing: { compactionPressureMin_MPa: 0, efficiencyFactorMin: 0, efficiencyFactorMax: 1 },
  water: { defaultWorkability: 'standard', phiMin: 0, phiMax: 1 },
  shrinkage: {
    defaultProfile_C: '110, 600, 800, 1000, 1200, 1400',
    defaultWaterCementRatio: 0.5,
    defaultCementContent: 0.1,
    defaultCementType: 'CAC',
    fractionMin: 0,
    fractionMax: 1,
    holdTimeMin_hours: 0,
  },
  blend: {
    qChoices: [0.21, 0.25, 0.27, 0.3, 0.33, 0.37],
    defaultQValues: [0.25, 0.3, 0.37],
    defaultMethods: ['Andreasen', 'FunkDinger'],
    defaultPackingModels: ['CPM'],
    defaultScenarios: ['Vibratable'],
    tableMaxHeight: 480,
    defaultWaterCementRatio: 0.35,
  },
  structureChartHeight: 320,
} as const;
